### ISSUE TITLE
Add course field to consult

### ISSUE THREAD

**Issue by Clarenceeey** [AY2425S1-CS2103T-F13-1/tp#134]
Lets the user know which course the consult is for. Course becomes a compulsory field for a consult

**Comment by notnotmax** [comment]
If time had allowed, this would've been worth considering putting on Lessons instead, but seeing the work necessary (need to adapt the code to lessons, modify storage, test cases, maybe even check a student is taking a course before adding them to a lesson of that course), I think we can just not do this.
