### ISSUE TITLE
TAHub v1.4 not Updating Deleted Students in Consultations

### ISSUE THREAD

**Issue by S-K-Y-Light** [AY2425S1-CS2103T-F13-1/tp#188]
Currently, Consultations has Students from the Student List.
However, it is possible to modify the Student List to `delete` the Student.
Yet, the changes to Students are not updated and reflected in the Consultations accordingly.

For Example, a Deleted Student will still remain in a Consultation if the Student was previously added to the Consultation.

As the Commands continue to change. We recommend doing a final check on ModelManager.java before the end of v1.5.

**Comment by notnotmax** [comment]
This is part of a bigger problem that could happen to Lessons as well. There is an obvious brute force solution where we iterate through all consultations and lessons every time a student is deleted. Hopefully people don't start having 10000 students and 100 classes or the program is going to freeze.
