### ISSUE TITLE
TAHub v1.4 Students with Multiple Courses Display

### ISSUE THREAD

**Issue by S-K-Y-Light** [AY2425S1-CS2103T-F13-1/tp#191]
Students with multiple courses will display Course Information awkwardly as below.

### Image
![image](https://github.com/user-attachments/assets/dc8bcd4d-b1c4-4567-8a21-cd42f11c8f9f)

**Comment by notnotmax** [comment]
This seems to already be fixed in the latest version of master.
![image](https://github.com/user-attachments/assets/30ad39f6-7a61-491f-9c4e-0f460f159bdf)
