### ISSUE TITLE
[PE-D][Tester D] Specifying name for addtoconsult and removefromconsult commands is case sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-1/tp#265]
As in title, user would expect this to be case insensitive, to be consistent with the find command earlier.

![image.png](https://raw.githubusercontent.com/ty4g1/ped/main/files/4fdab20a-78b5-4ccf-a24a-e38d868f16c7.png)

If this is intended, it should be clearly stated in the UG.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ty4g1/ped#6

**Comment by S-K-Y-Light** [comment]
Update UG/DG: Names are Case Sensitive
