### ISSUE TITLE
[PE-D][Tester C] Error message for deletelesson

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-1/tp#267]
![image.png](https://raw.githubusercontent.com/jiayr99/ped/main/files/7df63a3a-a565-47eb-8867-ea626936986b.png)

![image.png](https://raw.githubusercontent.com/jiayr99/ped/main/files/8d7a0d59-0323-4d21-8aa2-943a1de895b4.png)

Might be better if "deletelesson 8" and "deletelesson 0" have the same error message, since both are invalid indexes.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jiayr99/ped#5

**Comment by S-K-Y-Light** [comment]
Update UG/DG: Indices >= 1 & < Interger.MAX_VALUE
