### ISSUE TITLE
[PE-D][Tester A] Name with special characters are not allowed in the app

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-1/tp#293]
There are people whose names contain "S/O", but "/" is disabled in current `add` command of students, which is a bit overly restricted.

![image.png](https://raw.githubusercontent.com/Rachelcoll/ped/main/files/52b00a35-48c5-4ea1-9d00-4a7221b3b643.png)

Suggestion:

Allow user to add special chracters like "/" and "-" in the name and relax the restrictions appropriately.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Rachelcoll/ped#13

**Comment by S-K-Y-Light** [comment]
Update UG/DG: Names do not Allow Special Characters (except `,` & Spaces)
