### ISSUE TITLE
[PE-D][Tester C] Symbols in user input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-1/tp#303]
![image.png](https://raw.githubusercontent.com/jiayr99/ped/main/files/2a42fb8f-9750-4dce-84f6-6996375c9202.png)

Wouldn't it make more sense that symbols like "s/o" be accepted as specifically for TA's it might be necessary for the student's full legal name to be input?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jiayr99/ped#9

**Comment by S-K-Y-Light** [comment]
Update UG/DG: Names do not Allow Special Characters (except `,` & Spaces)
