### ISSUE TITLE
[PE-D][Tester C] Find command UG issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-1/tp#306]
![image.png](https://raw.githubusercontent.com/jiayr99/ped/main/files/476c740d-ce31-49a7-aa44-72e03066623a.png)

![image.png](https://raw.githubusercontent.com/jiayr99/ped/main/files/3afc02da-6193-4285-af26-03cc5617f0ac.png)

UG says find "input" should work, but the app says it is an invalid command format. (though it is updated in the DG)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: jiayr99/ped#12

**Comment by S-K-Y-Light** [comment]
Update UG/DG: Improve Find Command
