### ISSUE TITLE
[PE-D][Tester C] DG Format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-1/tp#307]
![image.png](https://raw.githubusercontent.com/jiayr99/ped/main/files/1b40647e-751f-4ad5-aba3-102bba588641.png)

DG would be easier to read if there was more spacing between the lines, and perhaps some keywords bolded.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: jiayr99/ped#13

**Comment by S-K-Y-Light** [comment]
Update UG/DG: Bold / Spaces. It's Optional, but a good recommendation from the Tester
